extends:
    - plugin:@mysticatea/es2015
    - plugin:@mysticatea/+node
    - plugin:@mysticatea/+modules
overrides:
    - files: "*.ts"
      rules:
          "@mysticatea/ts/no-use-before-define": "off"
    - files: "typings/**"
      rules:
          node/no-missing-import:
              - error
              - allowModules:
                    - estree
